# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5eb72597f7b3ceb58de8fd11793b0f7ba4a58116d7d193dd282b9b23076d1b5bbda658979c2cb24b9336d806fef6d475791ca852659d7896e4cf611a4a5d528

test:
  secret_key_base: 3925390d0ce8575cde2bf3e29d31f858a0480889fd077a3fa65ef2b280627252037dfa60c24ef2aabf991c83ebb156895752b2d3c95877022c9da638fd6788f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
